// data-seed.js
const initialPaises = [
  { id: Date.now() + 101, nombre: 'Afganistán', ciudades: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'] },
  { id: Date.now() + 102, nombre: 'Albania', ciudades: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan'] },
  { id: Date.now() + 103, nombre: 'Alemania', ciudades: ['Berlín', 'Múnich', 'Hamburgo', 'Fráncfort', 'Colonia', 'Stuttgart'] },
  { id: Date.now() + 104, nombre: 'Andorra', ciudades: ['Andorra la Vieja', 'Escaldes-Engordany', 'Encamp', 'La Massana'] },
  { id: Date.now() + 105, nombre: 'Angola', ciudades: ['Luanda', 'Huambo', 'Benguela', 'Lubango', 'Cabinda'] },
  { id: Date.now() + 106, nombre: 'Antigua y Barbuda', ciudades: ['Saint John', 'All Saints', 'Liberta', 'English Harbour'] },
  { id: Date.now() + 107, nombre: 'Arabia Saudita', ciudades: ['Riad', 'Yeda', 'La Meca', 'Medina', 'Dammam'] },
  { id: Date.now() + 108, nombre: 'Argelia', ciudades: ['Argel', 'Orán', 'Constantina', 'Annaba', 'Tremecén'] },
  { id: Date.now() + 109, nombre: 'Argentina', ciudades: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata'] },
  { id: Date.now() + 110, nombre: 'Armenia', ciudades: ['Ereván', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Hrazdan'] },
  { id: Date.now() + 111, nombre: 'Australia', ciudades: ['Sídney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaida', 'Canberra'] },
  { id: Date.now() + 112, nombre: 'Austria', ciudades: ['Viena', 'Graz', 'Linz', 'Salzburgo', 'Innsbruck', 'Klagenfurt'] },
  { id: Date.now() + 113, nombre: 'Azerbaiyán', ciudades: ['Bakú', 'Ganyá', 'Sumqayit', 'Mingachevir', 'Lankaran'] },
  { id: Date.now() + 114, nombre: 'Bahamas', ciudades: ['Nassau', 'Freeport', 'West End', 'Cooperstown', 'Marsh Harbour'] },
  { id: Date.now() + 115, nombre: 'Bangladés', ciudades: ['Daca', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal'] },
  { id: Date.now() + 116, nombre: 'Barbados', ciudades: ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown'] },
  { id: Date.now() + 117, nombre: 'Baréin', ciudades: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Isa Town'] },
  { id: Date.now() + 118, nombre: 'Bélgica', ciudades: ['Bruselas', 'Amberes', 'Gante', 'Charleroi', 'Lieja', 'Brujas'] },
  { id: Date.now() + 119, nombre: 'Belice', ciudades: ['Belmopán', 'Ciudad de Belice', 'San Ignacio', 'Orange Walk', 'Corozal'] },
  { id: Date.now() + 120, nombre: 'Benín', ciudades: ['Porto-Novo', 'Cotonú', 'Parakou', 'Djougou', 'Abomey'] },
  { id: Date.now() + 121, nombre: 'Bielorrusia', ciudades: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'] },
  { id: Date.now() + 122, nombre: 'Birmania (Myanmar)', ciudades: ['Naipyidó', 'Yangón', 'Mandalay', 'Bago', 'Mawlamyine'] },
  { id: Date.now() + 123, nombre: 'Bolivia', ciudades: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'Oruro', 'Potosí'] },
  { id: Date.now() + 124, nombre: 'Bosnia y Herzegovina', ciudades: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'] },
  { id: Date.now() + 125, nombre: 'Botsuana', ciudades: ['Gaborone', 'Francistown', 'Molepolole', 'Serowe', 'Maun'] },
  { id: Date.now() + 126, nombre: 'Brasil', ciudades: ['Brasilia', 'São Paulo', 'Río de Janeiro', 'Salvador', 'Fortaleza', 'Belo Horizonte'] },
  { id: Date.now() + 127, nombre: 'Brunéi', ciudades: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'] },
  { id: Date.now() + 128, nombre: 'Bulgaria', ciudades: ['Sofía', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora'] },
  { id: Date.now() + 129, nombre: 'Burkina Faso', ciudades: ['Uagadugú', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora'] },
  { id: Date.now() + 130, nombre: 'Burundi', ciudades: ['Buyumbura', 'Gitega', 'Ngozi', 'Rutana', 'Muyinga'] },
  { id: Date.now() + 131, nombre: 'Bután', ciudades: ['Timbu', 'Phuntsholing', 'Paro', 'Punakha', 'Wangdue'] },
  { id: Date.now() + 132, nombre: 'Cabo Verde', ciudades: ['Praia', 'Mindelo', 'Santa Maria', 'São Filipe', 'Assomada'] },
  { id: Date.now() + 133, nombre: 'Camboya', ciudades: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampong Cham'] },
  { id: Date.now() + 134, nombre: 'Camerún', ciudades: ['Yaundé', 'Duala', 'Garoua', 'Bamenda', 'Maroua', 'Bafoussam'] },
  { id: Date.now() + 135, nombre: 'Canadá', ciudades: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton'] },
  { id: Date.now() + 136, nombre: 'Catar', ciudades: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal'] },
  { id: Date.now() + 137, nombre: 'Chad', ciudades: ['Yamena', 'Moundou', 'Sarh', 'Abéché', 'Kélo'] },
  { id: Date.now() + 138, nombre: 'Chile', ciudades: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Viña del Mar'] },
  { id: Date.now() + 139, nombre: 'China', ciudades: ['Pekín', 'Shanghái', 'Cantón', 'Shenzhen', 'Chengdú', 'Hong Kong'] },
  { id: Date.now() + 140, nombre: 'Chipre', ciudades: ['Nicosia', 'Limassol', 'Lárnaca', 'Pafos', 'Famagusta'] },
  { id: Date.now() + 141, nombre: 'Ciudad del Vaticano', ciudades: ['Ciudad del Vaticano'] },
  { id: Date.now() + 142, nombre: 'Colombia', ciudades: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira', 'Manizales', 'Ibagué', 'Santa Marta', 'Villavicencio', 'Cúcuta', 'Neiva', 'Pasto', 'Armenia', 'Montería', 'Sincelejo', 'Popayán', 'Tunja', 'Palmira', 'Tuluá', 'Buga', 'Cartago', 'Girardot', 'Soacha', 'Zipaquirá', 'Facatativá', 'Chía', 'Sogamoso', 'Duitama', 'Riohacha', 'San Andrés', 'Leticia', 'Florencia', 'Quibdó', 'Yopal', 'Arauca', 'Mocoa', 'Puerto Carreño', 'Inírida', 'Mitú'] },
  { id: Date.now() + 143, nombre: 'Comoras', ciudades: ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Itsandra'] },
  { id: Date.now() + 144, nombre: 'Congo', ciudades: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Ouesso'] },
  { id: Date.now() + 145, nombre: 'Corea del Norte', ciudades: ['Pionyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan', 'Sinuiju'] },
  { id: Date.now() + 146, nombre: 'Corea del Sur', ciudades: ['Seúl', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju'] },
  { id: Date.now() + 147, nombre: 'Costa de Marfil', ciudades: ['Yamusukro', 'Abiyán', 'Bouaké', 'Daloa', 'Korhogo'] },
  { id: Date.now() + 148, nombre: 'Costa Rica', ciudades: ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia', 'Limón'] },
  { id: Date.now() + 149, nombre: 'Croacia', ciudades: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik'] },
  { id: Date.now() + 150, nombre: 'Cuba', ciudades: ['La Habana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara', 'Matanzas'] },
  { id: Date.now() + 151, nombre: 'Dinamarca', ciudades: ['Copenhague', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers'] },
  { id: Date.now() + 152, nombre: 'Yibuti', ciudades: ['Yibuti', 'Ali Sabieh', 'Tadjoura', 'Obock', 'Dikhil'] },
  { id: Date.now() + 153, nombre: 'Dominica', ciudades: ['Roseau', 'Portsmouth', 'Marigot', 'Saint Joseph', 'Castle Bruce'] },
  { id: Date.now() + 154, nombre: 'Ecuador', ciudades: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Ambato', 'Manta'] },
  { id: Date.now() + 155, nombre: 'Egipto', ciudades: ['El Cairo', 'Alejandría', 'Giza', 'Luxor', 'Asuán', 'Port Said'] },
  { id: Date.now() + 156, nombre: 'El Salvador', ciudades: ['San Salvador', 'Santa Ana', 'San Miguel', 'Soyapango', 'Mejicanos'] },
  { id: Date.now() + 157, nombre: 'Emiratos Árabes Unidos', ciudades: ['Abu Dabi', 'Dubái', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah'] },
  { id: Date.now() + 158, nombre: 'Eritrea', ciudades: ['Asmara', 'Massaúa', 'Keren', 'Assab', 'Mendefera'] },
  { id: Date.now() + 159, nombre: 'Eslovaquia', ciudades: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra', 'Trnava'] },
  { id: Date.now() + 160, nombre: 'Eslovenia', ciudades: ['Liubliana', 'Maribor', 'Celje', 'Kranj', 'Koper', 'Novo Mesto'] },
  { id: Date.now() + 161, nombre: 'España', ciudades: ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Málaga'] },
  { id: Date.now() + 162, nombre: 'Estados Unidos', ciudades: ['Nueva York', 'Los Ángeles', 'Miami', 'Chicago', 'Houston', 'San Francisco'] },
  { id: Date.now() + 163, nombre: 'Estonia', ciudades: ['Tallin', 'Tartu', 'Narva', 'Pärnu', 'Viljandi', 'Rakvere'] },
  { id: Date.now() + 164, nombre: 'Etiopía', ciudades: ['Adís Abeba', 'Dire Dawa', 'Mekelle', 'Adama', 'Gondar', 'Bahir Dar'] },
  { id: Date.now() + 165, nombre: 'Filipinas', ciudades: ['Manila', 'Quezon City', 'Cebú', 'Dávao', 'Zamboanga', 'Bacólod'] },
  { id: Date.now() + 166, nombre: 'Finlandia', ciudades: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Turku', 'Oulu'] },
  { id: Date.now() + 167, nombre: 'Fiyi', ciudades: ['Suva', 'Nadi', 'Lautoka', 'Labasa', 'Ba'] },
  { id: Date.now() + 168, nombre: 'Francia', ciudades: ['París', 'Marsella', 'Lyon', 'Toulouse', 'Niza', 'Burdeos'] },
  { id: Date.now() + 169, nombre: 'Gabón', ciudades: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'] },
  { id: Date.now() + 170, nombre: 'Gambia', ciudades: ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni'] },
  { id: Date.now() + 171, nombre: 'Georgia', ciudades: ['Tiflis', 'Batumi', 'Kutaisi', 'Rustavi', 'Zugdidi', 'Gori'] },
  { id: Date.now() + 172, nombre: 'Ghana', ciudades: ['Acra', 'Kumasi', 'Sekondi-Takoradi', 'Tamale', 'Tema', 'Cape Coast'] },
  { id: Date.now() + 173, nombre: 'Granada', ciudades: ['Saint George', 'Grenville', 'Gouyave', 'Victoria', 'Sauteurs'] },
  { id: Date.now() + 174, nombre: 'Grecia', ciudades: ['Atenas', 'Salónica', 'Patras', 'Heraclión', 'Lárisa', 'Volos'] },
  { id: Date.now() + 175, nombre: 'Guatemala', ciudades: ['Ciudad de Guatemala', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'Antigua'] },
  { id: Date.now() + 176, nombre: 'Guinea', ciudades: ['Conakri', 'Nzérékoré', 'Kankan', 'Kindia', 'Boké', 'Labé'] },
  { id: Date.now() + 177, nombre: 'Guinea Ecuatorial', ciudades: ['Malabo', 'Bata', 'Ebebiyín', 'Aconibe', 'Evinayong'] },
  { id: Date.now() + 178, nombre: 'Guinea-Bisáu', ciudades: ['Bisáu', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama'] },
  { id: Date.now() + 179, nombre: 'Guyana', ciudades: ['Georgetown', 'Linden', 'New Amsterdam', 'Bartica', 'Lethem'] },
  { id: Date.now() + 180, nombre: 'Haití', ciudades: ['Puerto Príncipe', 'Cap-Haïtien', 'Jacmel', 'Gonaïves', 'Les Cayes'] },
  { id: Date.now() + 181, nombre: 'Honduras', ciudades: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso'] },
  { id: Date.now() + 182, nombre: 'Hungría', ciudades: ['Budapest', 'Debrecen', 'Szeged', 'Pécs', 'Győr', 'Miskolc'] },
  { id: Date.now() + 183, nombre: 'India', ciudades: ['Nueva Delhi', 'Bombay', 'Calcuta', 'Madrás', 'Bangalore', 'Hyderabad'] },
  { id: Date.now() + 184, nombre: 'Indonesia', ciudades: ['Yakarta', 'Surabaya', 'Bandung', 'Medán', 'Yogyakarta', 'Denpasar'] },
  { id: Date.now() + 185, nombre: 'Irak', ciudades: ['Bagdad', 'Basora', 'Mosul', 'Erbil', 'Kirkuk', 'Suleimaniya'] },
  { id: Date.now() + 186, nombre: 'Irán', ciudades: ['Teherán', 'Mashhad', 'Isfahán', 'Tabriz', 'Shiraz', 'Qom'] },
  { id: Date.now() + 187, nombre: 'Irlanda', ciudades: ['Dublín', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda'] },
  { id: Date.now() + 188, nombre: 'Islandia', ciudades: ['Reikiavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Reykjanesbær'] },
  { id: Date.now() + 189, nombre: 'Islas Marshall', ciudades: ['Majuro', 'Ebeye', 'Jaluit', 'Wotje', 'Enewetak'] },
  { id: Date.now() + 190, nombre: 'Islas Salomón', ciudades: ['Honiara', 'Gizo', 'Auki', 'Kirakira', 'Lata'] },
  { id: Date.now() + 191, nombre: 'Israel', ciudades: ['Jerusalén', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Asdod'] },
  { id: Date.now() + 192, nombre: 'Italia', ciudades: ['Roma', 'Milán', 'Nápoles', 'Turín', 'Florencia', 'Venecia'] },
  { id: Date.now() + 193, nombre: 'Jamaica', ciudades: ['Kingston', 'Montego Bay', 'Spanish Town', 'Mandeville', 'Ocho Ríos'] },
  { id: Date.now() + 194, nombre: 'Japón', ciudades: ['Tokio', 'Osaka', 'Yokohama', 'Nagoya', 'Sapporo', 'Kioto'] },
  { id: Date.now() + 195, nombre: 'Jordania', ciudades: ['Amán', 'Zarqa', 'Irbid', 'Aqaba', 'Mafraq', 'Salt'] },
  { id: Date.now() + 196, nombre: 'Kazajistán', ciudades: ['Nur-sultán', 'Almaty', 'Shymkent', 'Karagandá', 'Aktobé', 'Taraz'] },
  { id: Date.now() + 197, nombre: 'Kenia', ciudades: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Malindi'] },
  { id: Date.now() + 198, nombre: 'Kirguistán', ciudades: ['Biskek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok', 'Naryn'] },
  { id: Date.now() + 199, nombre: 'Kiribati', ciudades: ['Tarawa Sur', 'Betio', 'Bikenibeu', 'Tabwakea', 'London'] },
  { id: Date.now() + 200, nombre: 'Kosovo', ciudades: ['Pristina', 'Prizren', 'Peja', 'Gjakova', 'Mitrovica', 'Ferizaj'] },
  { id: Date.now() + 201, nombre: 'Kuwait', ciudades: ['Kuwait City', 'Ahmadi', 'Hawalli', 'Farwaniya', 'Salmiya', 'Jahra'] },
  { id: Date.now() + 202, nombre: 'Laos', ciudades: ['Vientián', 'Luang Prabang', 'Savannakhet', 'Pakse', 'Thakhek'] },
  { id: Date.now() + 203, nombre: 'Lesoto', ciudades: ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse', 'Mohales Hoek'] },
  { id: Date.now() + 204, nombre: 'Letonia', ciudades: ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava', 'Jurmala', 'Ventspils'] },
  { id: Date.now() + 205, nombre: 'Líbano', ciudades: ['Beirut', 'Trípoli', 'Sidón', 'Tiro', 'Baalbek', 'Jounieh'] },
  { id: Date.now() + 206, nombre: 'Liberia', ciudades: ['Monrovia', 'Gbarnga', 'Buchanan', 'Harper', 'Zwedru'] },
  { id: Date.now() + 207, nombre: 'Libia', ciudades: ['Trípoli', 'Bengasi', 'Misurata', 'Tobruk', 'Sabha', 'Zawiya'] },
  { id: Date.now() + 208, nombre: 'Liechtenstein', ciudades: ['Vaduz', 'Schaan', 'Balzers', 'Eschen', 'Mauren', 'Triesen'] },
  { id: Date.now() + 209, nombre: 'Lituania', ciudades: ['Vilna', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus'] },
  { id: Date.now() + 210, nombre: 'Luxemburgo', ciudades: ['Luxemburgo', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'] },
  { id: Date.now() + 211, nombre: 'Macedonia del Norte', ciudades: ['Skopie', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo', 'Ohrid'] },
  { id: Date.now() + 212, nombre: 'Madagascar', ciudades: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Toliara'] },
  { id: Date.now() + 213, nombre: 'Malasia', ciudades: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Johor Bahru', 'Malaca', 'Kuching'] },
  { id: Date.now() + 214, nombre: 'Malaui', ciudades: ['Lilongüe', 'Blantyre', 'Mzuzu', 'Zomba', 'Salima'] },
  { id: Date.now() + 215, nombre: 'Maldivas', ciudades: ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi', 'Thinadhoo'] },
  { id: Date.now() + 216, nombre: 'Malí', ciudades: ['Bamako', 'Sikasso', 'Kayes', 'Mopti', 'Segú', 'Tombuctú'] },
  { id: Date.now() + 217, nombre: 'Malta', ciudades: ['La Valeta', 'Birkirkara', 'Qormi', 'Sliema', 'Mosta', 'Rabat'] },
  { id: Date.now() + 218, nombre: 'Marruecos', ciudades: ['Rabat', 'Casablanca', 'Marrakech', 'Fez', 'Tánger', 'Agadir'] },
  { id: Date.now() + 219, nombre: 'Mauricio', ciudades: ['Port Louis', 'Beau Bassin-Rose Hill', 'Curepipe', 'Quatre Bornes', 'Vacoas'] },
  { id: Date.now() + 220, nombre: 'Mauritania', ciudades: ['Nuakchot', 'Nouadhibou', 'Kaédi', 'Zouérate', 'Rosso', 'Selibaby'] },
  { id: Date.now() + 221, nombre: 'México', ciudades: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Cancún'] },
  { id: Date.now() + 222, nombre: 'Micronesia', ciudades: ['Palikir', 'Weno', 'Kolonia', 'Tofol', 'Colonia'] },
  { id: Date.now() + 223, nombre: 'Moldavia', ciudades: ['Chisináu', 'Tiráspol', 'Bălți', 'Bender', 'Cahul', 'Ungheni'] },
  { id: Date.now() + 224, nombre: 'Mónaco', ciudades: ['Mónaco', 'La Condamine', 'Montecarlo', 'Fontvieille'] },
  { id: Date.now() + 225, nombre: 'Mongolia', ciudades: ['Ulán Bator', 'Darkhan', 'Erdenet', 'Khovd', 'Ölgii', 'Choibalsan'] },
  { id: Date.now() + 226, nombre: 'Montenegro', ciudades: ['Podgorica', 'Nikšić', 'Bar', 'Herceg Novi', 'Budva', 'Kotor'] },
  { id: Date.now() + 227, nombre: 'Mozambique', ciudades: ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Quelimane'] },
  { id: Date.now() + 228, nombre: 'Namibia', ciudades: ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Rundu', 'Otjiwarongo'] },
  { id: Date.now() + 229, nombre: 'Nauru', ciudades: ['Yaren', 'Denigomodu', 'Baiti', 'Nibok', 'Uaboe'] },
  { id: Date.now() + 230, nombre: 'Nepal', ciudades: ['Katmandú', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar', 'Janakpur'] },
  { id: Date.now() + 231, nombre: 'Nicaragua', ciudades: ['Managua', 'León', 'Granada', 'Matagalpa', 'Masaya', 'Chinandega'] },
  { id: Date.now() + 232, nombre: 'Níger', ciudades: ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua', 'Diffa'] },
  { id: Date.now() + 233, nombre: 'Nigeria', ciudades: ['Abuya', 'Lagos', 'Kano', 'Ibadán', 'Benin City', 'Port Harcourt'] },
  { id: Date.now() + 234, nombre: 'Noruega', ciudades: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Fredrikstad'] },
  { id: Date.now() + 235, nombre: 'Nueva Zelanda', ciudades: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin'] },
  { id: Date.now() + 236, nombre: 'Omán', ciudades: ['Mascate', 'Salalah', 'Sohar', 'Sur', 'Nizwa', 'Ibri'] },
  { id: Date.now() + 237, nombre: 'Países Bajos', ciudades: ['Ámsterdam', 'Róterdam', 'La Haya', 'Utrecht', 'Eindhoven', 'Groninga'] },
  { id: Date.now() + 238, nombre: 'Pakistán', ciudades: ['Islamabad', 'Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Multán'] },
  { id: Date.now() + 239, nombre: 'Palaos', ciudades: ['Ngerulmud', 'Koror', 'Meyungs', 'Airai', 'Kloulklubed'] },
  { id: Date.now() + 240, nombre: 'Palestina', ciudades: ['Ramala', 'Gaza', 'Hebrón', 'Nablus', 'Belén', 'Jericó'] },
  { id: Date.now() + 241, nombre: 'Panamá', ciudades: ['Ciudad de Panamá', 'Colón', 'David', 'Santiago', 'Chitré', 'Penonomé'] },
  { id: Date.now() + 242, nombre: 'Papúa Nueva Guinea', ciudades: ['Puerto Moresby', 'Lae', 'Mount Hagen', 'Madang', 'Kokopo'] },
  { id: Date.now() + 243, nombre: 'Paraguay', ciudades: ['Asunción', 'Ciudad del Este', 'Encarnación', 'Caaguazú', 'Pedro Juan Caballero'] },
  { id: Date.now() + 244, nombre: 'Perú', ciudades: ['Lima', 'Arequipa', 'Cusco', 'Trujillo', 'Piura', 'Chiclayo'] },
  { id: Date.now() + 245, nombre: 'Polonia', ciudades: ['Varsovia', 'Cracovia', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk'] },
  { id: Date.now() + 246, nombre: 'Portugal', ciudades: ['Lisboa', 'Oporto', 'Braga', 'Coímbra', 'Funchal', 'Faro'] },
  { id: Date.now() + 247, nombre: 'Reino Unido', ciudades: ['Londres', 'Manchester', 'Birmingham', 'Edimburgo', 'Glasgow', 'Liverpool'] },
  { id: Date.now() + 248, nombre: 'República Centroafricana', ciudades: ['Bangui', 'Bimbo', 'Berbérati', 'Bouar', 'Bambari', 'Bossangoa'] },
  { id: Date.now() + 249, nombre: 'República Checa', ciudades: ['Praga', 'Brno', 'Ostrava', 'Pilsen', 'Liberec', 'Olomouc'] },
  { id: Date.now() + 250, nombre: 'República Democrática del Congo', ciudades: ['Kinsasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Bukavu', 'Goma'] },
  { id: Date.now() + 251, nombre: 'República Dominicana', ciudades: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís', 'Puerto Plata'] },
  { id: Date.now() + 252, nombre: 'Ruanda', ciudades: ['Kigali', 'Butare', 'Gisenyi', 'Ruhengeri', 'Cyangugu'] },
  { id: Date.now() + 253, nombre: 'Rumania', ciudades: ['Bucarest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanza', 'Brașov'] },
  { id: Date.now() + 254, nombre: 'Rusia', ciudades: ['Moscú', 'San Petersburgo', 'Novosibirsk', 'Ekaterimburgo', 'Kazán', 'Vladivostok'] },
  { id: Date.now() + 255, nombre: 'Samoa', ciudades: ['Apia', 'Salelologa', 'Vaiusu', 'Faleula', 'Siusega'] },
  { id: Date.now() + 256, nombre: 'San Cristóbal y Nieves', ciudades: ['Basseterre', 'Charlestown', 'Sandy Point Town', 'Cayon', 'Tabernacle'] },
  { id: Date.now() + 257, nombre: 'San Marino', ciudades: ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano', 'Fiorentino'] },
  { id: Date.now() + 258, nombre: 'San Vicente y las Granadinas', ciudades: ['Kingstown', 'Georgetown', 'Barrouallie', 'Chateaubelair', 'Layou'] },
  { id: Date.now() + 259, nombre: 'Santa Lucía', ciudades: ['Castries', 'Gros Islet', 'Vieux Fort', 'Micoud', 'Soufrière'] },
  { id: Date.now() + 260, nombre: 'Santo Tomé y Príncipe', ciudades: ['Santo Tomé', 'Neves', 'Santana', 'Trindade', 'Guadalupe'] },
  { id: Date.now() + 261, nombre: 'Senegal', ciudades: ['Dakar', 'Thiès', 'Saint-Louis', 'Kaolack', 'Ziguinchor', 'Mbour'] },
  { id: Date.now() + 262, nombre: 'Serbia', ciudades: ['Belgrado', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin'] },
  { id: Date.now() + 263, nombre: 'Seychelles', ciudades: ['Victoria', 'Beau Vallon', 'Anse Royale', 'Cascade', 'Baie Lazare'] },
  { id: Date.now() + 264, nombre: 'Sierra Leona', ciudades: ['Freetown', 'Bo', 'Kenema', 'Makeni', 'Koidu', 'Port Loko'] },
  { id: Date.now() + 265, nombre: 'Singapur', ciudades: ['Singapur'] },
  { id: Date.now() + 266, nombre: 'Siria', ciudades: ['Damasco', 'Alepo', 'Homs', 'Latakia', 'Hama', 'Deir ez-Zor'] },
  { id: Date.now() + 267, nombre: 'Somalia', ciudades: ['Mogadiscio', 'Hargeisa', 'Kismayo', 'Baidoa', 'Garoowe', 'Bosaso'] },
  { id: Date.now() + 268, nombre: 'Sri Lanka', ciudades: ['Sri Jayawardenapura Kotte', 'Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo'] },
  { id: Date.now() + 269, nombre: 'Suazilandia', ciudades: ['Mbabane', 'Manzini', 'Big Bend', 'Malkerns', 'Nhlangano'] },
  { id: Date.now() + 270, nombre: 'Sudáfrica', ciudades: ['Pretoria', 'Ciudad del Cabo', 'Johannesburgo', 'Durban', 'Puerto Elizabeth', 'Bloemfontein'] },
  { id: Date.now() + 271, nombre: 'Sudán', ciudades: ['Jartum', 'Omdurmán', 'Port Sudan', 'Kassala', 'Nyala', 'El-Obeid'] },
  { id: Date.now() + 272, nombre: 'Sudán del Sur', ciudades: ['Yuba', 'Malakal', 'Wau', 'Bor', 'Rumbek', 'Bentiu'] },
  { id: Date.now() + 273, nombre: 'Suecia', ciudades: ['Estocolmo', 'Gotemburgo', 'Malmö', 'Uppsala', 'Linköping', 'Västerås'] },
  { id: Date.now() + 274, nombre: 'Suiza', ciudades: ['Berna', 'Zúrich', 'Ginebra', 'Basilea', 'Lausana', 'Lucerna'] },
  { id: Date.now() + 275, nombre: 'Surinam', ciudades: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo', 'Brokopondo'] },
  { id: Date.now() + 276, nombre: 'Tailandia', ciudades: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hat Yai', 'Nakhon Ratchasima'] },
  { id: Date.now() + 277, nombre: 'Taiwán', ciudades: ['Taipéi', 'Kaohsiung', 'Taichung', 'Tainan', 'Taoyuan', 'Keelung'] },
  { id: Date.now() + 278, nombre: 'Tanzania', ciudades: ['Dodoma', 'Dar es Salaam', 'Mwanza', 'Arusha', 'Zanzíbar', 'Mbeya'] },
  { id: Date.now() + 279, nombre: 'Tayikistán', ciudades: ['Dusambé', 'Khujand', 'Kulob', 'Bokhtar', 'Istaravshan', 'Panjakent'] },
  { id: Date.now() + 280, nombre: 'Timor Oriental', ciudades: ['Dili', 'Baucau', 'Same', 'Liquiçá', 'Maliana', 'Suai'] },
  { id: Date.now() + 281, nombre: 'Togo', ciudades: ['Lomé', 'Kara', 'Sokodé', 'Atakpamé', 'Kpalimé', 'Bassar'] },
  { id: Date.now() + 282, nombre: 'Tonga', ciudades: ['Nukualofa', 'Neiafu', 'Pangai', 'Haveluloto', 'Vaini'] },
  { id: Date.now() + 283, nombre: 'Trinidad y Tobago', ciudades: ['Puerto España', 'San Fernando', 'Arima', 'Chaguanas', 'Tunapuna'] },
  { id: Date.now() + 284, nombre: 'Túnez', ciudades: ['Túnez', 'Sfax', 'Susa', 'Bizerta', 'Kairuán', 'Gabes'] },
  { id: Date.now() + 285, nombre: 'Turkmenistán', ciudades: ['Asjabad', 'Türkmenabat', 'Daşoguz', 'Mary', 'Balkanabat', 'Bayramaly'] },
  { id: Date.now() + 286, nombre: 'Turquía', ciudades: ['Ankara', 'Estambul', 'Esmirna', 'Bursa', 'Adana', 'Antalya'] },
  { id: Date.now() + 287, nombre: 'Tuvalu', ciudades: ['Funafuti', 'Vaiaku', 'Asau', 'Lolua', 'Savave'] },
  { id: Date.now() + 288, nombre: 'Ucrania', ciudades: ['Kiev', 'Járkiv', 'Odesa', 'Dnipro', 'Leópolis', 'Zaporiyia'] },
  { id: Date.now() + 289, nombre: 'Uganda', ciudades: ['Kampala', 'Gulu', 'Lira', 'Mbale', 'Jinja', 'Mbarara'] },
  { id: Date.now() + 290, nombre: 'Uruguay', ciudades: ['Montevideo', 'Salto', 'Punta del Este', 'Colonia del Sacramento', 'Rivera', 'Maldonado'] },
  { id: Date.now() + 291, nombre: 'Uzbekistán', ciudades: ['Taskent', 'Samarcanda', 'Bujará', 'Namangán', 'Andiján', 'Ferganá'] },
  { id: Date.now() + 292, nombre: 'Vanuatu', ciudades: ['Port Vila', 'Luganville', 'Norsup', 'Isangel', 'Sola'] },
  { id: Date.now() + 293, nombre: 'Venezuela', ciudades: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana'] },
  { id: Date.now() + 294, nombre: 'Vietnam', ciudades: ['Hanói', 'Ho Chi Minh', 'Da Nang', 'Hai Phong', 'Huế', 'Nha Trang'] },
  { id: Date.now() + 295, nombre: 'Yemen', ciudades: ['Saná', 'Adén', 'Taiz', 'Hodeida', 'Mukalla', 'Ibb'] },
  { id: Date.now() + 296, nombre: 'Zambia', ciudades: ['Lusaka', 'Kitwe', 'Ndola', 'Chingola', 'Livingstone', 'Kabwe'] },
  { id: Date.now() + 298, nombre: 'Zimbabue', ciudades: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Masvingo'] }
];

const initialCategories = [
  { id: Date.now() + 1, nombre: 'Rock', descripcion: 'Conciertos de rock y metal' },
  { id: Date.now() + 2, nombre: 'Electrónica', descripcion: 'Eventos con DJs y música electrónica' },
  { id: Date.now() + 3, nombre: 'Pop', descripcion: 'Conciertos comerciales y festivales pop' },
  { id: Date.now() + 4, nombre: 'Jazz', descripcion: 'Música jazz y blues en vivo' },
  { id: Date.now() + 5, nombre: 'Clásica', descripcion: 'Conciertos de música clásica y orquestal' },
  { id: Date.now() + 6, nombre: 'Reguetón', descripcion: 'Artistas de reguetón y trap latino' },
  { id: Date.now() + 7, nombre: 'Salsa', descripcion: 'Salsa, bachata y ritmos caribeños' },
  { id: Date.now() + 8, nombre: 'Indie', descripcion: 'Bandas independientes y alternativas' },
  { id: Date.now() + 9, nombre: 'Festival', descripcion: 'Festivales multigénero al aire libre' }
];

function ensureSeedData() {
  const categorias = loadCategorias();
  if (!categorias.length) {
    saveCategorias(initialCategories);
  }

  const paises = loadPaises();
  if (!paises.length || paises.length < 100) {
    savePaises(initialPaises);
  }

  const eventos = loadEventos();
  if (!eventos.length) {
    const storedCategorias = loadCategorias();
    const storedPaises = loadPaises();
    const colombiaId = storedPaises.find(p => p.nombre === 'Colombia')?.id || initialPaises.find(p => p.nombre === 'Colombia')?.id;
    const seedEvents = [
      {
        id: Date.now() + 11,
        codigo: 'EVT001',
        nombre: 'Infernal Rock Night',
        categoriaId: storedCategorias[0]?.id || initialCategories[0].id,
        paisId: colombiaId,
        precio: 120000,
        fecha: '2026-11-10',
        hora: '20:00',
        ciudad: 'Bogotá',
        imagen: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?fit=crop&w=800&q=80',
        descripcion: 'Una noche de rock con bandas nacionales y sonido potente.'
      },
      {
        id: Date.now() + 12,
        codigo: 'EVT002',
        nombre: 'Electro Vibes',
        categoriaId: storedCategorias[1]?.id || initialCategories[1].id,
        paisId: colombiaId,
        precio: 95000,
        fecha: '2026-12-05',
        hora: '22:00',
        ciudad: 'Medellín',
        imagen: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?fit=crop&w=800&q=80',
        descripcion: 'Festival con DJs, luces láser y ambiente nocturno.'
      },
      {
        id: Date.now() + 13,
        codigo: 'EVT003',
        nombre: 'Pop Dreams',
        categoriaId: storedCategorias[2]?.id || initialCategories[2].id,
        paisId: colombiaId,
        precio: 108000,
        fecha: '2026-10-18',
        hora: '19:30',
        ciudad: 'Cali',
        imagen: 'https://images.unsplash.com/photo-1512362856338-5405fbe5e443?fit=crop&w=800&q=80',
        descripcion: 'Un show pop con artistas emergentes y sonidos energéticos.'
      },
      {
        id: Date.now() + 14,
        codigo: 'EVT004',
        nombre: 'Digital Circus',
        categoriaId: storedCategorias[8]?.id || initialCategories[8].id,
        paisId: colombiaId,
        precio: 150000,
        fecha: '2026-12-20',
        hora: '21:00',
        ciudad: 'Bogotá',
        imagen: 'https://images.unsplash.com/photo-1516559828984-fef4973811b9?fit=crop&w=800&q=80',
        descripcion: 'Un espectáculo circense digital con visuals, luces y música electrónica en vivo.'
      }
    ];
    saveEventos(seedEvents);
  }

  if (!loadCarrito().length) {
    saveCarrito([]);
  }

  if (!loadVentas().length) {
    saveVentas([]);
  }
}

ensureSeedData();
